In [1]:
# This is Lecture03 - Exercise 1
# of the "Data Science" class at Technische Hochschule Rosenheim

# Pokemon Dataset

In this exercise you will be analysing a dataset about Pokemon.
<img src="figures/pokemon.png" alt="Pikatchu" align="right" width="200"/>

### Intro to Pokemon
Pokémon is a media franchise managed by The Pokémon Company, a Japanese consortium between Nintendo, Game Freak, and Creatures. While the franchise copyright is shared by all three companies, Nintendo is the sole owner of the trademark. The franchise was created by Satoshi Tajiri in 1995, and is centered on fictional creatures called "Pokémon", which humans, known as Pokémon Trainers, catch and train to battle each other for sport.

The name Pokémon is the romanized contraction of the Japanese brand Pocket Monsters. The term Pokémon, in addition to referring to the Pokémon franchise itself, also collectively refers to the 721 known fictional species that have made appearances in Pokémon media as of the release of the sixth generation titles Pokémon X and Y. "Pokémon" is identical in both the singular and plural, as is each individual species name; it is grammatically correct to say "one Pokémon" and "many Pokémon", as well as "one Pikachu" and "many Pikachu". (source: wikipedia.com)

### The Dataset
You can find the data in three files in the 'data' directory. This are the raw attributes that are used for calculating how much damage an attack will do in the games. This dataset is about the Pokemon games (NOT Pokemon cards or Pokemon Go).

1) 'pokemon_ids.npy' contains an int ndarray of the ID for each Pokemon

2) 'pokemon_names.npy' contains a string ndarray of the name of each Pokemon (Hint: to `load` this file, you need to set the named parameter `allow_pickle` to `True`, as strings are objects)

3) 'pokemon_stats.npy' contains a ndarray with 6 columns for each Pokemon

- HP: hit points, or health, defines how much damage a Pokemon can withstand before fainting
- Attack: the base modifier for normal attacks (eg. Scratch, Punch)
- Defense: the base damage resistance against normal attacks
- SP Atk: special attack, the base modifier for special attacks (e.g. fire blast, bubble beam)
- SP Def: the base damage resistance against special attacks
- Speed: determines which Pokemon attacks first each round


### Exercises 1

* 1a) load the dataset into three numpy arrays 'ids', 'names' and 'stats'. Verfiy the datatypes of each array.

* 1b) how many rows do you expect the array to have? verify your assumption!

* 1c) inspect the first 10 rows and the last 10 rows - do you notice anything important? Find an explanation for your observation!


In [1]:
import numpy as np

In [37]:
## ---------- SOLUTION 1a
pokemon_ids = np.load("pokemon_ids.npy")
pokemon_names = np.load("pokemon_names.npy", allow_pickle=True)
pokemon_stats = np.load("pokemon_stats.npy")
print(type(pokemon_ids))
print(type(pokemon_names))
print(type(pokemon_stats))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [9]:
## ---------- SOLUTION 1b
print(len(pokemon_ids))
print(len(pokemon_names))
print(len(pokemon_stats))

800
800
800


In [12]:
## ---------- SOLUTION 1c
print(pokemon_ids[:10])
print(pokemon_names[:10])
print(pokemon_stats[:10])

[1 2 3 3 4 5 6 6 6 7]
['Bulbasaur' 'Ivysaur' 'Venusaur' 'VenusaurMega Venusaur' 'Charmander'
 'Charmeleon' 'Charizard' 'CharizardMega Charizard X'
 'CharizardMega Charizard Y' 'Squirtle']
[[ 45  49  49  65  65  45]
 [ 60  62  63  80  80  60]
 [ 80  82  83 100 100  80]
 [ 80 100 123 122 120  80]
 [ 39  52  43  60  50  65]
 [ 58  64  58  80  65  80]
 [ 78  84  78 109  85 100]
 [ 78 130 111 130  85 100]
 [ 78 104  78 159 115 100]
 [ 44  48  65  50  64  43]]


In [15]:
print(pokemon_ids[-10:])
print(pokemon_names[-10:])
print(pokemon_stats[-10:])

[714 715 716 717 718 719 719 720 720 721]
['Noibat' 'Noivern' 'Xerneas' 'Yveltal' 'Zygarde50% Forme' 'Diancie'
 'DiancieMega Diancie' 'HoopaHoopa Confined' 'HoopaHoopa Unbound'
 'Volcanion']
[[ 40  30  35  45  40  55]
 [ 85  70  80  97  80 123]
 [126 131  95 131  98  99]
 [126 131  95 131  98  99]
 [108 100 121  81  95  95]
 [ 50 100 150 100 150  50]
 [ 50 160 110 160 110 110]
 [ 80 110  60 150 130  70]
 [ 80 160  60 170 130  80]
 [ 80 110 120 130  90  70]]


### Exercises 2

* 2a) find the ids and names of all Pokemon with hitpoints above 150
* 2b) find the names of all Pokemon that have a higher Attack than Defense (the "attackers")

In [44]:
## ---------- SOLUTION 2a
bool_index = (pokemon_stats[:, 0] > 150)
print(*zip(pokemon_ids[bool_index], pokemon_names[bool_index]))

(113, 'Chansey') (143, 'Snorlax') (202, 'Wobbuffet') (242, 'Blissey') (321, 'Wailord') (594, 'Alomomola')


In [66]:
## ---------- SOLUTION 2b
bool_index = (pokemon_stats[:, 1] > pokemon_stats[:, 2])
pokemon_attacker = np.array((pokemon_ids[bool_index], pokemon_names[bool_index]))
print(pokemon_attacker.shape)
print(pokemon_attacker)

(2, 433)
[[4 5 6 6 6 13 15 15 16 17 18 19 20 21 22 23 24 25 26 31 32 33 34 37 38
  39 40 41 42 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 63 64 65 66 67
  68 69 70 71 72 73 77 78 83 84 85 88 89 92 93 94 96 97 98 99 103 106 107
  112 115 115 118 119 123 124 125 126 127 127 128 130 130 131 133 134 135
  136 141 142 142 143 145 146 147 148 149 150 150 150 155 156 157 158 160
  161 162 167 168 169 172 174 177 178 190 192 193 196 198 201 203 209 210
  211 212 212 214 214 215 216 217 220 221 223 224 225 228 229 234 238 239
  240 243 244 246 247 248 248 250 252 253 254 254 255 256 257 257 258 259
  260 260 261 262 264 265 267 274 275 276 277 282 286 289 291 292 293 294
  295 296 297 308 309 310 311 313 315 318 319 319 320 321 322 323 323 328
  329 330 331 332 335 336 338 339 340 341 342 347 348 352 353 354 354 359
  359 362 371 373 373 376 381 381 382 382 383 383 384 384 386 386 386 387
  388 389 390 391 392 396 397 398 399 400 402 403 404 405 407 408 409 414
  418 419 423 424 425 426 427 4

---